### ISSUE TITLE
Capturas de pantalla con scroll

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#402]
Deberás encontrar un complemento para el navegador que permita realizar capturas con scroll incluso en iFrames.

Para poder dar buena la tarea, deberá demostrarse que sirve para capturar los resultados de CodeCademy

**Comment by profeIAP** [comment]
Igual resulta de utilidad [la siguiente aplicación](https://www.maketecheasier.com/take-scrolling-screenshots-android/amp/) (no la he probado, símplemente la he encontrado)

**Comment by Rgm13** [comment]
En android tenía una aplicación la cual si me dejaba hacer capturas en
scroll, es mas nose si el modo de captura en scroll que ya trae android te
sirve para iframe.
Las capturas de html y ccs las hice con el movil con esa opción pero para
el navegador no encuentro extensiones que hagan esa función.

**Comment by Rgm13** [comment]
Tiene buena pinta esa aplicación.

**Comment by profeIAP** [comment]
Me alegra que te guste... realmente nos sirve cualquier solución (móvil o escritorio)

La idea es contar con una alternativa la próxima vez que algún compañero vuestro necesite hacer dichas capturas (realmente me da igual decirle que lo haga con el móvil que con el portátil 😉)

No, si al final vas a coger de nuevo la tarea 😂

**Comment by Rgm13** [comment]
En cuanto haga mañana el examen de historia me pongo a probar aplicaciones😂

**Comment by profeIAP** [comment]
Vistos los problemas que está dando una tarea que parecía tan sencilla inicialmente, subimos la "apuesta" y la catalogamos como _reto_

¿Algún valiente en la "sala"? 👍

**Comment by profeIAP** [comment]
Aunque engorroso (y requerir el uso en el móvil del modo "escritorio" para que funcione) podemos dar por buena la solución.

Enhorabuena, Raúl

**Comment by Rgm13** [comment]
Gracias.
Pd: el modo escritorio no es necesario

El 5 feb. 2018 4:51 p. m., "Profesor IAP" <notifications@github.com>
escribió:

Aunque engorroso (y requerir el uso en el móvil del modo "escritorio" para
que funcione) podemos dar por buena la solución.

Enhorabuena, Raúl

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/profeIAP/retados/issues/402#issuecomment-363126238>,
or mute
the thread

**Comment by profeIAP** [comment]
Pues sin él, no me funciona en Chrome

>
