### ISSUE TITLE
Anotar el hash del email a restablecer

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#443]
Tras la implementación de la tarea #442, anotar el parámetro $hash recibido, para que pueda ser [renderizado por la vista](https://github.com/profeIAP/retados/blob/bab208d89fc231eb6c3429c10621822bc4ad2fcf/index.php#L359)

Para evitar confusiones, usa _hash_ como nombre del parámetro proporcionado a la vista.

**Comment by profeIAP** [comment]
Casi lo has logrado... al renderizar la vista, se debe proporcionar un array (en tu caso con una entrada única a la que denominarás "hash")

**Comment by juankagb00** [comment]
Suelto una tarea porque ahora tengo 3 que hago?

El 9 feb. 2018 18:28, "Profesor IAP" <notifications@github.com> escribió:

Reopened #443 <https://github.com/profeIAP/retados/issues/443>.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/profeIAP/retados/issues/443#event-1467130456>, or mute
the thread

**Comment by profeIAP** [comment]
No te preocupes, como indico en Google Classroom, se ha concedido un "periodo de gracia" debido a la "parada técnica" que experimenté ayer... tienes el lunes para poder resolver (y probarlo) 😉

**Comment by profeIAP** [comment]
Aquí un ejemplo de [cómo hacerlo](https://github.com/profeIAP/retados/blob/bab208d89fc231eb6c3429c10621822bc4ad2fcf/index.php#L272-L274)

**Comment by profeIAP** [comment]
Uyyy... se añade comentario en el commit

**Comment by profeIAP** [comment]
Fino, fino.
Gracias Juan Carlos
